version: '3.8'

services:
  my_data_app:
    image: attidiany/my_data_app:latest
    container_name: my_data_app
    ports:
      - "8501:8501"
    restart: unless-stopped
    environment:
      STREAMLIT_SERVER_PORT: 8501
      STREAMLIT_SERVER_ENABLECORS: false
    volumes:
      - ./data:/app/data  # Monte le dossier data s’il existe
